# MicroSim Default Scenario

world:
  size: [100.0, 100.0] # meters (x, y)
  resolution: 0.5 # meters per grid cell

robots:
  drone:
    initial_pose:
      x: 0.0
      y: 0.0
      z: 1.0
      yaw: 0.0
    max_velocity: 3.0
    max_accel: 2.0

  rover:
    initial_pose:
      x: -5.0
      y: 0.0
      theta: 0.0
    max_velocity: 1.0
    max_omega: 1.57

sensors:
  gps:
    rate_hz: 10.0
    noise_std: 0.1 # meters

  range:
    rate_hz: 20.0
    max_range: 10.0
    noise_std: 0.05

  camera:
    width: 128
    height: 128
    fov_deg: 90.0
    rate_hz: 2.0

radio:
  max_range: 100.0
  base_latency: 0.05 # seconds
  jitter: 0.01
  packet_loss: 0.01

# Obstacles and features
features:
  - type: obstacle
    position: [10.0, 10.0]
    radius: 3.0
    height: 5.0

  - type: hazard
    position: [-10.0, 15.0]
    radius: 5.0
    height: 0.0

  - type: target
    position: [20.0, -10.0]
    radius: 2.0
    height: 0.0
