# MicroSim Default Scenario

world:
  size: [100.0, 100.0] # meters (x, y)
  resolution: 0.1 # meters per grid cell (finer detail: was 0.5m, now 0.1m)

robots:
  drone:
    initial_pose:
      x: 0.0
      y: 0.0
      z: 1.0
      yaw: 0.0
    max_velocity: 3.0
    max_accel: 2.0

  rover:
    initial_pose:
      x: -5.0
      y: 0.0
      theta: 0.0
    max_velocity: 1.0
    max_omega: 1.57

sensors:
  gps:
    rate_hz: 10.0
    noise_std: 0.1 # meters

  range:
    rate_hz: 20.0
    max_range: 10.0
    noise_std: 0.05

  camera:
    width: 256
    height: 256
    fov_deg: 60.0
    rate_hz: 2.0

radio:
  max_range: 100.0
  base_latency: 0.05 # seconds
  jitter: 0.01
  packet_loss: 0.01

# Obstacles and features (mix of large and small for varied detail)
features:
  # Large features (original)
  - type: obstacle
    position: [10.0, 10.0]
    radius: 3.0
    height: 5.0

  - type: hazard
    position: [-10.0, 15.0]
    radius: 5.0
    height: 0.0

  - type: target
    position: [20.0, -10.0]
    radius: 2.0
    height: 0.0

  # Small obstacles (rocks, trees)
  - type: obstacle
    position: [5.0, 3.0]
    radius: 0.5
    height: 2.0

  - type: obstacle
    position: [7.0, 5.0]
    radius: 0.3
    height: 1.5

  - type: obstacle
    position: [12.0, 8.0]
    radius: 0.8
    height: 3.0

  # Small hazards (puddles, rough terrain)
  - type: hazard
    position: [2.0, -5.0]
    radius: 1.0
    height: 0.0

  - type: hazard
    position: [-5.0, -8.0]
    radius: 0.7
    height: 0.0

  - type: hazard
    position: [8.0, -3.0]
    radius: 1.5
    height: 0.0

  # Small targets (landing pads, markers)
  - type: target
    position: [0.0, 5.0]
    radius: 0.5
    height: 0.0

  - type: target
    position: [-3.0, 8.0]
    radius: 0.8
    height: 0.0

  - type: target
    position: [15.0, -5.0]
    radius: 0.6
    height: 0.0
